config/routes.rb
Rails.application.routes.draw do

resources :things

root 'things#index'

end

app/models/thing.rb
class Thing < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController

  def index
    @things = Thing.all
  end

  def new
    @thing = Thing.new
  end

  def create
    @thing = Thing.new(thing_params)
    if @thing.save
      redirect_to things_path
    else
      render :new
    end
  end

  def show
    @thing = Thing.find(params[:id])
  end

  def edit
    @thing = Thing.find(params[:id])
  end

  def update
    @thing = Thing.find(params[:id])
    if @thing.update_attributes(thing_params)
      redirect_to thing_url(@thing.id)
    else
      render :edit
    end
  end

  def destroy
    @thing = Thing.find(params[:id])
    @thing.destroy
    redirect_to things_path
  end

  private
  def thing_params
    params.require(:thing).permit(:title, :description, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coolstuff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/things/edit.html.erb
<h1> Edit your Thing! </h1>

<%= link_to "Back to Things", things_url %>

<%= form_for @thing do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
<img src="<%= @thing.url %>">
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

app/views/things/index.html.erb
<h1> Inventory of "Things"</h1>

<%= link_to "Add new Thing", new_thing_url %>

  <% @things.each do |thing| %>
    <h3> Photo Title: <%= thing.title %></h3>
    <%= link_to image_tag(thing.url), thing_url(thing.id) %>
    <p> Description: <%= thing.description %></p>
    <br>
    <br>
  <% end %>

app/views/things/new.html.erb
<h1> New Thing! </h1>

<%= link_to "Back to Things", things_url %>

<%= form_for @thing do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/things/show.html.erb
<h1> Show specific Thing</h1>

<%= link_to "Back to Things", things_url %>

    <h3> Photo Title: <%= @thing.title %></h3>
    <p> <%= link_to "Edit Thing", edit_thing_url(@thing.id) %>
        <%= link_to "Delete Thing", delete_thing_path(@thing), method: :delete, data: {confirm: "Are you sure you want to delete this thing?"} %></p>
    <img src="<%= @thing.url %>">
    <p> Description: <%= @thing.description %></p>